### ISSUE TITLE
[Feature request] Syntax highlighting in code snippets / examples.

### ISSUE THREAD

**Issue by absorber** [progit/progit#923]
Right now the code snippets (for instance in example sections) are all red, which is confusing for a lot of new people. So why not just use something like [gist embedding](https://github.com/blairvanderhoof/gist-embed)?

**Comment by jnavila** [comment]
This is more an issue of the git-scm site. Please forward your issue to git/git-scm.com.

**Comment by absorber** [comment]
Oops, sorry! I was here because of a recommendation. Apparently someone over at #git got things a bit tangled up.
