### ISSUE TITLE
Default core-editor documentation.

### ISSUE THREAD

**Issue by uNiversaI** [progit/progit#942]
Following up on https://github.com/git-for-windows/git/issues/278 where currently there is a issue of edits being terminated prematurely before their concluded while on Windows with notepad++ as a default editor not set as core.editor with ```-multiInst```

I had a look at https://github.com/progit/progit/blob/master/en/07-customizing-git/01-chapter7.markdown (presuming this is right place to put this?

I would suggest that some note or documentation on how to workaround the issue which seems to be resolved  by adding/settings Notepad++ with ```-multiInst``` until this is resolved in core and the installer detect and sets the editor properly as to avoid the issue in first place.

The reason this would be best in meanwhile is because https://github.com/msysgit/msysgit/issues/218 is now over a year old and no solution exists in core atm.

x86
```
 git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst" 
```
x64
```
 git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst" 
```

I dont mid making the edit and submitting the PR if someone points me to right page in case

**Comment by YueLinHo** [comment]
> I had a look at https://github.com/progit/progit/blob/master/en/07-customizing-git/01-chapter7.markdown (presuming this is right place to put this?

There is [Pro Git 2](https://github.com/progit/progit2) and [core.editor](https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/config.asc#coreeditor)

**Comment by uNiversaI** [comment]
> There is Pro Git 2 and core.editor

Right thanks, do you think this sort of documentation would be suited to add to https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/config.asc#coreeditor?

**Comment by YueLinHo** [comment]
> Much better target thank you.

You're welcome.

> Do you think this sort of documentation would be suited to add to core.editor?

In my opinion, as a user, it's good.
Actually, stuff on Windows is rarely mentioned on this book.
IIRC, [Installing on Windows](https://github.com/progit/progit2/blob/master/book/01-introduction/sections/installing.asc#installing-on-windows) is one of them.

> Shall we close this and open this request there for discussion?

Better to close here, open there.
And you could open a PR there. :)

**Comment by YueLinHo** [comment]
> Do you think this sort of documentation would be suited to add to core.editor?

Perhaps somethings like [the section "Credential Storage"](Do you think this sort of documentation would be suited to add to core.editor?)

**Comment by uNiversaI** [comment]
> Actually, stuff on Windows is rarely mentioned on this book.
> IIRC, Installing on Windows is one of them.

I dont often use windows, mainly is virtual machine windows guests but when I do this issue https://github.com/git-for-windows/git/issues/278 is enough to pull hairs out. 

> Better to close here, open there.
> And you could open a PR there. :)

Yes I think so, will do.

> Perhaps somethings like the section "[Credential Storage](https://github.com/progit/progit/issues/Do%20you%20think%20this%20sort%20of%20documentation%20would%20be%20suited%20to%20add%20to%20core.editor?)"

That link is bad.

**Comment by uNiversaI** [comment]
closing here in favor of https://github.com/progit/progit2/issues/365

**Comment by YueLinHo** [comment]
>Perhaps somethings like the section "Credential Storage"
That link is bad.

Corrected it in [my comment](https://github.com/progit/progit/issues/942#issuecomment-132475545). 
([Credential Storage](https://github.com/progit/progit2/blob/master/book/07-git-tools/sections/credentials.asc))

**Comment by uNiversaI** [comment]
mmm I dontthink credential Storage docs has anything to do with this... Any reason why you suggested it?

**Comment by YueLinHo** [comment]
yep, it is not related to core.editor. But you could refer its format or the way to mention stuff on windows.

**Comment by uNiversaI** [comment]
> yep, it is not related to core.editor. But you could refer its format or the way to mention stuff on windows.

Ah yes, understood, good thinking.
