### ISSUE TITLE
git-svn examples depend on non-existing svn repro on googlecode

### ISSUE THREAD

**Issue by Treverix** [progit/progit#952]
Chapter 8 contains the line

`$ svnsync init file:///tmp/test-svn http://progit-example.googlecode.com/svn/`

which fails because the remote url is invalid. Has the svn repro been moved? Currently it's not possible to reproduce the examples.

**Comment by lamlylom90** [comment]
Ok

**Comment by lamlylom90** [comment]
Good

**Comment by lamlylom90** [comment]
Ok

**Comment by lamlylom90** [comment]
Good

**Comment by lamlylom90** [comment]
Good

**Comment by lamlylom90** [comment]
Ok

**Comment by lamlylom90** [comment]
Good

**Comment by jnavila** [comment]
Thanks for your report.

We no longer work on the first edition of Progit. Please check the project of the second edition https://github.com/progit/progit2 if your issue applies to it.

**Comment by danieleasoni** [comment]
You can get the archived project from here: https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/progit-example/repo.svndump.gz

To load it, you can follow my instructions at https://github.com/danieleasoni/git-svn-example
